[[set]]
identifier = "control-window"
description = "Control the window"

permissions = [
	"core:window:allow-close",
	"core:window:allow-hide",
	"core:window:allow-show",
	"core:window:allow-minimize",
	"core:window:allow-maximize",
	"core:window:allow-unmaximize",
	"core:window:allow-start-dragging",
	"core:window:allow-toggle-maximize",
	"core:window:allow-internal-toggle-maximize",
	"core:window:allow-set-decorations",
]